In [2]:
from dataset import Dataset

In [3]:
dataset = Dataset()

=> loading coco asset: dataset/coco-safe-licenses.pickle
=> loading coco object - dataset/annotations/captions_train2017.json
loading annotations into memory...
Done (t=1.46s)
creating index...
index created!


In [4]:
from skimage.exposure import match_histograms, histogram
from PIL import Image
import matplotlib.pyplot as plt
from utils import imshow
import random
import numpy as np

vars = {}

im_nums = [0, 1, 2, 3, 4]
variations = np.zeros((len(im_nums), 3))
# hists = histogram(np.asarray(Image.open(f"out/{j}.png")))
histograms = []
hist_avg = np.zeros((3,256))

histograms = []

num_ims = 10
dims = [512,512]


for idx, j in enumerate(num_ims):
    img = np.asarray(dataset.get_coco_example().get_image(dims))
    print(img.shape)
    hist = histogram(img, channel_axis=-1)
    histograms.append(hist[0])
    plt.figure(figsize=(10,4))
    plt.subplot(1,2,1)
    plt.hist(hist[0][0],color='red')
    plt.hist(hist[0][1],color='green')
    plt.hist(hist[0][2],color='blue')
    plt.subplot(1,2,2)
    plt.imshow(img)
    plt.show()
    print(hist[0].shape)
    break
    for c in range(3):
        hist_avg[c, :] += hist[0][c, :]

# hist_avg /= len(im_nums)

# plt.hist(hist_avg[0],color='red')
# plt.hist(hist_avg[1],color='green')
# plt.hist(hist_avg[2],color='blue')
# plt.show()

# test = np.mean(histograms, axis=0) - hist_avg

# plt.hist(test[0],color='red')
# plt.hist(test[1],color='green')
# plt.hist(test[2],color='blue')
# plt.show()

# print("YOP")

# diffs = [np.sum(np.abs(h - hist_avg)) for h in histograms]

# idx_min = np.argmin(diffs)
# img = np.asarray(Image.open(f"out/{im_nums[idx_min]}.png"))
# imshow(img)
# print(np.argmin(diffs))

# test_diffs = [np.sum(np.abs(h - np.mean(histograms))) for h in histograms]

# idx_min = np.argmin(test_diffs)
# img = np.asarray(Image.open(f"out/{im_nums[idx_min]}.png"))
# imshow(img)
# print(np.argmin(test_diffs))


TypeError: 'int' object is not iterable

In [36]:
from skimage.exposure import match_histograms, histogram
from PIL import Image
import matplotlib.pyplot as plt
from utils import imshow
import random
import numpy as np

vars = {}

im_nums = [0, 1, 2, 3, 4]
variations = np.zeros((len(im_nums), 3))
# hists = histogram(np.asarray(Image.open(f"out/{j}.png")))
histograms = []
hist_avg = np.zeros((3,256))

histograms = []

num_ims = 100
dims = [512,512]

bad_imgs = []
good_imgs = []
for _ in range(1000):

    img = np.asarray(dataset.get_coco_example().load_image(dims))
    # print(img.flags)
    try:
        hist = histogram(img, channel_axis=-1)
        good_imgs.append(img)
        # histograms.append(hist[0])
    except Exception as e:
        
        print(f"{e}\n{img}\n{len(bad_imgs)}")
        bad_imgs.append(img)
        # break
    # plt.figure(figsize=(10,4))
    # plt.subplot(1,2,1)
    # plt.hist(hist[0][0],color='red')
    # plt.hist(hist[0][1],color='green')
    # plt.hist(hist[0][2],color='blue')
    # plt.subplot(1,2,2)
    # plt.imshow(img)
    # plt.show()
    # print(hist[0].shape)
    # break
    # for c in range(3):
    #     hist_avg[c, :] += hist[0][c, :]

# hist_avg /= len(im_nums)

# plt.hist(hist_avg[0],color='red')
# plt.hist(hist_avg[1],color='green')
# plt.hist(hist_avg[2],color='blue')
# plt.show()

# test = np.mean(histograms, axis=0) - hist_avg

# plt.hist(test[0],color='red')
# plt.hist(test[1],color='green')
# plt.hist(test[2],color='blue')
# plt.show()

# print("YOP")

# diffs = [np.sum(np.abs(h - hist_avg)) for h in histograms]

# idx_min = np.argmin(diffs)
# img = np.asarray(Image.open(f"out/{im_nums[idx_min]}.png"))
# imshow(img)
# print(np.argmin(diffs))

# test_diffs = [np.sum(np.abs(h - np.mean(histograms))) for h in histograms]

# idx_min = np.argmin(test_diffs)
# img = np.asarray(Image.open(f"out/{im_nums[idx_min]}.png"))
# imshow(img)
# print(np.argmin(test_diffs))


all input arrays must have the same shape
[[[50 48 53]
  [51 49 53]
  [55 53 56]
  ...
  [44 44 44]
  [47 47 47]
  [48 48 48]]

 [[50 48 53]
  [51 49 53]
  [55 53 56]
  ...
  [46 46 46]
  [47 47 47]
  [47 48 48]]

 [[49 47 51]
  [50 48 51]
  [52 51 54]
  ...
  [46 45 46]
  [46 45 45]
  [46 45 45]]

 ...

 [[86 81 85]
  [87 82 86]
  [86 81 85]
  ...
  [47 43 46]
  [43 42 43]
  [46 46 47]]

 [[88 83 87]
  [87 82 86]
  [87 82 86]
  ...
  [47 46 47]
  [42 42 43]
  [46 46 47]]

 [[89 84 88]
  [88 83 87]
  [89 84 88]
  ...
  [48 48 50]
  [43 43 45]
  [47 47 49]]]
0
all input arrays must have the same shape
[[[172 172 164]
  [172 172 164]
  [172 172 164]
  ...
  [176 173 166]
  [176 173 166]
  [175 172 165]]

 [[172 172 164]
  [172 172 164]
  [172 172 164]
  ...
  [176 173 166]
  [176 173 166]
  [175 172 165]]

 [[172 172 164]
  [172 172 164]
  [172 172 164]
  ...
  [175 172 165]
  [176 173 166]
  [174 171 164]]

 ...

 [[ 69  83 123]
  [ 68  84 120]
  [ 72  89 122]
  ...
  [ 69  96 124]
  [ 

In [40]:
print(img.flags)

  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False



In [49]:
flag = "UPDATEIFCOPY"
bad_f = [img.flags[flag] for img in bad_imgs]
good_f = [img.flags[flag] for img in good_imgs]

print(bad_f)
print(good_f)
# for img in bad_imgs:
    
#     print(img.shape, img.dtype, img.itemsize, img.flags)
#     # imshow(img)

[False, False, False, False, False, False, False, False, False, False, False, False, False]
[False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, Fals

/tmp/ipykernel_265259/485270817.py:2: DeprecationWarning: UPDATEIFCOPY deprecated, use WRITEBACKIFCOPY instead
  bad_f = [img.flags[flag] for img in bad_imgs]
/tmp/ipykernel_265259/485270817.py:3: DeprecationWarning: UPDATEIFCOPY deprecated, use WRITEBACKIFCOPY instead
  good_f = [img.flags[flag] for img in good_imgs]
